In [1]:
import fiberForge
from fiberForge.build import calculate_average_rotation_translation
import mbuild as mb
import numpy as np

In [8]:
R, t = calculate_average_rotation_translation("protofibril.pdb")
# build the structure
chain = mb.load("protofibril.pdb")
print(R, t)
structure = fiberForge.build.build_fibril(chain.children[0], R, t, 8)
display(structure.visualize())
display(chain.visualize())

[[ 9.97764714e-01 -5.49658603e-02  1.52376145e-04]
 [ 5.53587788e-02  9.97692892e-01  1.22304216e-03]
 [ 3.16198495e-03 -4.43240857e-03  9.98807831e-01]] [ 5.28806182 -5.02002915  5.1149611 ]


3Dmol.js failed to load for some reason. Please check your browser console for error messages.

3Dmol.js failed to load for some reason. Please check your browser console for error messages.